# Config file for automatic testing at travis-ci.org
language: python
sudo: false
python:
- "3.6"
- "3.5"
- "2.7"
- "pypy"
install:
- pip install -U .
- pip install -r dev-requirements.txt
script: invoke test
jobs:
  include:
  - stage: PyPI Release
    if: tag IS present
    python: "3.6"
    env: []
    # Override before_install, install, and script to no-ops
    before_install: true
    install: true
    script: echo "Releasing to PyPI..."
    after_success: true
    deploy:
      provider: pypi
      user: sloria
      on:
        tags: true
      distributions: sdist bdist_wheel
      password:
        secure: LOpaUZEDeJadNiejr04i9bhFQRi8cYbKSo58gBlUEv/oxh6l4uPHm04zDH9GXqgs7kgcRVryLq1+LPFd3sKS1bASMSzdRs0P7SmsQugJVGxvzILw6QNwj5f8pK9ol8qyqSZHmVWoPr8nPwoLB++xIE+B9ZNkaejFr/2zNvLqOWg=
